server:
  port: 8083
  servlet:
    context-path: /test

jdbc:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
  username: root
  password: 2314

mybatis:
  configPath: mybatis-config.xml
  mapperPath: /mapper/**.xml
  entityPackage: com.cyan.test.entity

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

upload: #文件上传配置
  location:  #配置默认文件保存位置
    windows: D:\Cyan\Places\FilePlaces\
    linux: /Cyan/Places/FilePlaces/

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB